//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//
//     Zmiany w tym pliku mogą spowodować niewłaściwe zachowanie i zostaną utracone
//     w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionDto", Namespace="http://tempuri.org/")]
    public partial class SessionDto : object
    {
        
        private int IdField;
        
        private string RoomNameField;
        
        private bool IsBusyField;
        
        private string FirstPlayerField;
        
        private string SecondPlayerField;
        
        private bool FirstPlayerOnTurnField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RoomName
        {
            get
            {
                return this.RoomNameField;
            }
            set
            {
                this.RoomNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool IsBusy
        {
            get
            {
                return this.IsBusyField;
            }
            set
            {
                this.IsBusyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FirstPlayer
        {
            get
            {
                return this.FirstPlayerField;
            }
            set
            {
                this.FirstPlayerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SecondPlayer
        {
            get
            {
                return this.SecondPlayerField;
            }
            set
            {
                this.SecondPlayerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool FirstPlayerOnTurn
        {
            get
            {
                return this.FirstPlayerOnTurnField;
            }
            set
            {
                this.FirstPlayerOnTurnField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BoardDto", Namespace="http://tempuri.org/")]
    public partial class BoardDto : object
    {
        
        private int PositionIndexField;
        
        private int PieceIdField;
        
        private int ColorIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PositionIndex
        {
            get
            {
                return this.PositionIndexField;
            }
            set
            {
                this.PositionIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int PieceId
        {
            get
            {
                return this.PieceIdField;
            }
            set
            {
                this.PieceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int ColorId
        {
            get
            {
                return this.ColorIdField;
            }
            set
            {
                this.ColorIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap
    {
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu GetSessionsResult z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSessions", ReplyAction="*")]
        ServiceReference1.GetSessionsResponse GetSessions(ServiceReference1.GetSessionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSessions", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetSessionsResponse> GetSessionsAsync(ServiceReference1.GetSessionsRequest request);
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu roomName z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostSession", ReplyAction="*")]
        ServiceReference1.PostSessionResponse PostSession(ServiceReference1.PostSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostSession", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.PostSessionResponse> PostSessionAsync(ServiceReference1.PostSessionRequest request);
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu secondPlayer z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSession", ReplyAction="*")]
        ServiceReference1.UpdateSessionResponse UpdateSession(ServiceReference1.UpdateSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSession", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.UpdateSessionResponse> UpdateSessionAsync(ServiceReference1.UpdateSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSession", ReplyAction="*")]
        bool DeleteSession(int sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSession", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteSessionAsync(int sessionId);
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu sessionDto z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveGameState", ReplyAction="*")]
        ServiceReference1.SaveGameStateResponse SaveGameState(ServiceReference1.SaveGameStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveGameState", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.SaveGameStateResponse> SaveGameStateAsync(ServiceReference1.SaveGameStateRequest request);
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu roomName z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGameState", ReplyAction="*")]
        ServiceReference1.GetGameStateResponse GetGameState(ServiceReference1.GetGameStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGameState", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetGameStateResponse> GetGameStateAsync(ServiceReference1.GetGameStateRequest request);
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu GetStartingBoardResult z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStartingBoard", ReplyAction="*")]
        ServiceReference1.GetStartingBoardResponse GetStartingBoard(ServiceReference1.GetStartingBoardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStartingBoard", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetStartingBoardResponse> GetStartingBoardAsync(ServiceReference1.GetStartingBoardRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSessionsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSessions", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetSessionsRequestBody Body;
        
        public GetSessionsRequest()
        {
        }
        
        public GetSessionsRequest(ServiceReference1.GetSessionsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSessionsRequestBody
    {
        
        public GetSessionsRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSessionsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSessionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetSessionsResponseBody Body;
        
        public GetSessionsResponse()
        {
        }
        
        public GetSessionsResponse(ServiceReference1.GetSessionsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSessionsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.SessionDto[] GetSessionsResult;
        
        public GetSessionsResponseBody()
        {
        }
        
        public GetSessionsResponseBody(ServiceReference1.SessionDto[] GetSessionsResult)
        {
            this.GetSessionsResult = GetSessionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostSessionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostSession", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.PostSessionRequestBody Body;
        
        public PostSessionRequest()
        {
        }
        
        public PostSessionRequest(ServiceReference1.PostSessionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostSessionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string roomName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstPlayer;
        
        public PostSessionRequestBody()
        {
        }
        
        public PostSessionRequestBody(string roomName, string firstPlayer)
        {
            this.roomName = roomName;
            this.firstPlayer = firstPlayer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostSessionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostSessionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.PostSessionResponseBody Body;
        
        public PostSessionResponse()
        {
        }
        
        public PostSessionResponse(ServiceReference1.PostSessionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostSessionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.SessionDto PostSessionResult;
        
        public PostSessionResponseBody()
        {
        }
        
        public PostSessionResponseBody(ServiceReference1.SessionDto PostSessionResult)
        {
            this.PostSessionResult = PostSessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSessionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSession", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.UpdateSessionRequestBody Body;
        
        public UpdateSessionRequest()
        {
        }
        
        public UpdateSessionRequest(ServiceReference1.UpdateSessionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSessionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string secondPlayer;
        
        public UpdateSessionRequestBody()
        {
        }
        
        public UpdateSessionRequestBody(int sessionId, string secondPlayer)
        {
            this.sessionId = sessionId;
            this.secondPlayer = secondPlayer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSessionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSessionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.UpdateSessionResponseBody Body;
        
        public UpdateSessionResponse()
        {
        }
        
        public UpdateSessionResponse(ServiceReference1.UpdateSessionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSessionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.SessionDto UpdateSessionResult;
        
        public UpdateSessionResponseBody()
        {
        }
        
        public UpdateSessionResponseBody(ServiceReference1.SessionDto UpdateSessionResult)
        {
            this.UpdateSessionResult = UpdateSessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveGameStateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveGameState", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.SaveGameStateRequestBody Body;
        
        public SaveGameStateRequest()
        {
        }
        
        public SaveGameStateRequest(ServiceReference1.SaveGameStateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveGameStateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.SessionDto sessionDto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ServiceReference1.BoardDto[] boardToSave;
        
        public SaveGameStateRequestBody()
        {
        }
        
        public SaveGameStateRequestBody(ServiceReference1.SessionDto sessionDto, ServiceReference1.BoardDto[] boardToSave)
        {
            this.sessionDto = sessionDto;
            this.boardToSave = boardToSave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveGameStateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveGameStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.SaveGameStateResponseBody Body;
        
        public SaveGameStateResponse()
        {
        }
        
        public SaveGameStateResponse(ServiceReference1.SaveGameStateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveGameStateResponseBody
    {
        
        public SaveGameStateResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGameStateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGameState", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetGameStateRequestBody Body;
        
        public GetGameStateRequest()
        {
        }
        
        public GetGameStateRequest(ServiceReference1.GetGameStateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGameStateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string roomName;
        
        public GetGameStateRequestBody()
        {
        }
        
        public GetGameStateRequestBody(int sessionId, string roomName)
        {
            this.sessionId = sessionId;
            this.roomName = roomName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGameStateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGameStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetGameStateResponseBody Body;
        
        public GetGameStateResponse()
        {
        }
        
        public GetGameStateResponse(ServiceReference1.GetGameStateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGameStateResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.BoardDto[] GetGameStateResult;
        
        public GetGameStateResponseBody()
        {
        }
        
        public GetGameStateResponseBody(ServiceReference1.BoardDto[] GetGameStateResult)
        {
            this.GetGameStateResult = GetGameStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStartingBoardRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStartingBoard", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetStartingBoardRequestBody Body;
        
        public GetStartingBoardRequest()
        {
        }
        
        public GetStartingBoardRequest(ServiceReference1.GetStartingBoardRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetStartingBoardRequestBody
    {
        
        public GetStartingBoardRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStartingBoardResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStartingBoardResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetStartingBoardResponseBody Body;
        
        public GetStartingBoardResponse()
        {
        }
        
        public GetStartingBoardResponse(ServiceReference1.GetStartingBoardResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStartingBoardResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.BoardDto[] GetStartingBoardResult;
        
        public GetStartingBoardResponseBody()
        {
        }
        
        public GetStartingBoardResponseBody(ServiceReference1.BoardDto[] GetStartingBoardResult)
        {
            this.GetStartingBoardResult = GetStartingBoardResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface WebServiceSoapChannel : ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<ServiceReference1.WebServiceSoap>, ServiceReference1.WebServiceSoap
    {
        
        /// <summary>
        /// Wdróż tę metodę częściową, aby skonfigurować punkt końcowy usługi.
        /// </summary>
        /// <param name="serviceEndpoint">Punkt końcowy do skonfigurowania</param>
        /// <param name="clientCredentials">Poświadczenia klienta</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), WebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.GetSessionsResponse ServiceReference1.WebServiceSoap.GetSessions(ServiceReference1.GetSessionsRequest request)
        {
            return base.Channel.GetSessions(request);
        }
        
        public ServiceReference1.SessionDto[] GetSessions()
        {
            ServiceReference1.GetSessionsRequest inValue = new ServiceReference1.GetSessionsRequest();
            inValue.Body = new ServiceReference1.GetSessionsRequestBody();
            ServiceReference1.GetSessionsResponse retVal = ((ServiceReference1.WebServiceSoap)(this)).GetSessions(inValue);
            return retVal.Body.GetSessionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetSessionsResponse> ServiceReference1.WebServiceSoap.GetSessionsAsync(ServiceReference1.GetSessionsRequest request)
        {
            return base.Channel.GetSessionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetSessionsResponse> GetSessionsAsync()
        {
            ServiceReference1.GetSessionsRequest inValue = new ServiceReference1.GetSessionsRequest();
            inValue.Body = new ServiceReference1.GetSessionsRequestBody();
            return ((ServiceReference1.WebServiceSoap)(this)).GetSessionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.PostSessionResponse ServiceReference1.WebServiceSoap.PostSession(ServiceReference1.PostSessionRequest request)
        {
            return base.Channel.PostSession(request);
        }
        
        public ServiceReference1.SessionDto PostSession(string roomName, string firstPlayer)
        {
            ServiceReference1.PostSessionRequest inValue = new ServiceReference1.PostSessionRequest();
            inValue.Body = new ServiceReference1.PostSessionRequestBody();
            inValue.Body.roomName = roomName;
            inValue.Body.firstPlayer = firstPlayer;
            ServiceReference1.PostSessionResponse retVal = ((ServiceReference1.WebServiceSoap)(this)).PostSession(inValue);
            return retVal.Body.PostSessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.PostSessionResponse> ServiceReference1.WebServiceSoap.PostSessionAsync(ServiceReference1.PostSessionRequest request)
        {
            return base.Channel.PostSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.PostSessionResponse> PostSessionAsync(string roomName, string firstPlayer)
        {
            ServiceReference1.PostSessionRequest inValue = new ServiceReference1.PostSessionRequest();
            inValue.Body = new ServiceReference1.PostSessionRequestBody();
            inValue.Body.roomName = roomName;
            inValue.Body.firstPlayer = firstPlayer;
            return ((ServiceReference1.WebServiceSoap)(this)).PostSessionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.UpdateSessionResponse ServiceReference1.WebServiceSoap.UpdateSession(ServiceReference1.UpdateSessionRequest request)
        {
            return base.Channel.UpdateSession(request);
        }
        
        public ServiceReference1.SessionDto UpdateSession(int sessionId, string secondPlayer)
        {
            ServiceReference1.UpdateSessionRequest inValue = new ServiceReference1.UpdateSessionRequest();
            inValue.Body = new ServiceReference1.UpdateSessionRequestBody();
            inValue.Body.sessionId = sessionId;
            inValue.Body.secondPlayer = secondPlayer;
            ServiceReference1.UpdateSessionResponse retVal = ((ServiceReference1.WebServiceSoap)(this)).UpdateSession(inValue);
            return retVal.Body.UpdateSessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.UpdateSessionResponse> ServiceReference1.WebServiceSoap.UpdateSessionAsync(ServiceReference1.UpdateSessionRequest request)
        {
            return base.Channel.UpdateSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.UpdateSessionResponse> UpdateSessionAsync(int sessionId, string secondPlayer)
        {
            ServiceReference1.UpdateSessionRequest inValue = new ServiceReference1.UpdateSessionRequest();
            inValue.Body = new ServiceReference1.UpdateSessionRequestBody();
            inValue.Body.sessionId = sessionId;
            inValue.Body.secondPlayer = secondPlayer;
            return ((ServiceReference1.WebServiceSoap)(this)).UpdateSessionAsync(inValue);
        }
        
        public bool DeleteSession(int sessionId)
        {
            return base.Channel.DeleteSession(sessionId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteSessionAsync(int sessionId)
        {
            return base.Channel.DeleteSessionAsync(sessionId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.SaveGameStateResponse ServiceReference1.WebServiceSoap.SaveGameState(ServiceReference1.SaveGameStateRequest request)
        {
            return base.Channel.SaveGameState(request);
        }
        
        public void SaveGameState(ServiceReference1.SessionDto sessionDto, ServiceReference1.BoardDto[] boardToSave)
        {
            ServiceReference1.SaveGameStateRequest inValue = new ServiceReference1.SaveGameStateRequest();
            inValue.Body = new ServiceReference1.SaveGameStateRequestBody();
            inValue.Body.sessionDto = sessionDto;
            inValue.Body.boardToSave = boardToSave;
            ServiceReference1.SaveGameStateResponse retVal = ((ServiceReference1.WebServiceSoap)(this)).SaveGameState(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.SaveGameStateResponse> ServiceReference1.WebServiceSoap.SaveGameStateAsync(ServiceReference1.SaveGameStateRequest request)
        {
            return base.Channel.SaveGameStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SaveGameStateResponse> SaveGameStateAsync(ServiceReference1.SessionDto sessionDto, ServiceReference1.BoardDto[] boardToSave)
        {
            ServiceReference1.SaveGameStateRequest inValue = new ServiceReference1.SaveGameStateRequest();
            inValue.Body = new ServiceReference1.SaveGameStateRequestBody();
            inValue.Body.sessionDto = sessionDto;
            inValue.Body.boardToSave = boardToSave;
            return ((ServiceReference1.WebServiceSoap)(this)).SaveGameStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.GetGameStateResponse ServiceReference1.WebServiceSoap.GetGameState(ServiceReference1.GetGameStateRequest request)
        {
            return base.Channel.GetGameState(request);
        }
        
        public ServiceReference1.BoardDto[] GetGameState(int sessionId, string roomName)
        {
            ServiceReference1.GetGameStateRequest inValue = new ServiceReference1.GetGameStateRequest();
            inValue.Body = new ServiceReference1.GetGameStateRequestBody();
            inValue.Body.sessionId = sessionId;
            inValue.Body.roomName = roomName;
            ServiceReference1.GetGameStateResponse retVal = ((ServiceReference1.WebServiceSoap)(this)).GetGameState(inValue);
            return retVal.Body.GetGameStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetGameStateResponse> ServiceReference1.WebServiceSoap.GetGameStateAsync(ServiceReference1.GetGameStateRequest request)
        {
            return base.Channel.GetGameStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetGameStateResponse> GetGameStateAsync(int sessionId, string roomName)
        {
            ServiceReference1.GetGameStateRequest inValue = new ServiceReference1.GetGameStateRequest();
            inValue.Body = new ServiceReference1.GetGameStateRequestBody();
            inValue.Body.sessionId = sessionId;
            inValue.Body.roomName = roomName;
            return ((ServiceReference1.WebServiceSoap)(this)).GetGameStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.GetStartingBoardResponse ServiceReference1.WebServiceSoap.GetStartingBoard(ServiceReference1.GetStartingBoardRequest request)
        {
            return base.Channel.GetStartingBoard(request);
        }
        
        public ServiceReference1.BoardDto[] GetStartingBoard()
        {
            ServiceReference1.GetStartingBoardRequest inValue = new ServiceReference1.GetStartingBoardRequest();
            inValue.Body = new ServiceReference1.GetStartingBoardRequestBody();
            ServiceReference1.GetStartingBoardResponse retVal = ((ServiceReference1.WebServiceSoap)(this)).GetStartingBoard(inValue);
            return retVal.Body.GetStartingBoardResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetStartingBoardResponse> ServiceReference1.WebServiceSoap.GetStartingBoardAsync(ServiceReference1.GetStartingBoardRequest request)
        {
            return base.Channel.GetStartingBoardAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetStartingBoardResponse> GetStartingBoardAsync()
        {
            ServiceReference1.GetStartingBoardRequest inValue = new ServiceReference1.GetStartingBoardRequest();
            inValue.Body = new ServiceReference1.GetStartingBoardRequestBody();
            return ((ServiceReference1.WebServiceSoap)(this)).GetStartingBoardAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://chesswebservice.azurewebsites.net/WebService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://chesswebservice.azurewebsites.net/WebService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebServiceSoap,
            
            WebServiceSoap12,
        }
    }
}
